# docker-compose exec kafka kafka-topics --topic the-topic --zookeeper zookeeper:32181 --create --partitions 1 --replication-factor 1
---
version: '2'

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    hostname: kafkaserver
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"

  webview:
    image: sourcelaborg/kafka-webview:latest
    ports:
      - "8080:8080"
    links:
      - kafkaserver

networks:
  default:
    driver: bridge